Dictionary
L4pki/travelline_practice_summer pull request #2
Opened 2024-07-07 08:34 UTC by L4pki

2024-07-22 07:38 UTC, daug32 requested changes
Поправишь коммент в Program.cs, и можешь мержить
Написано в целом хорошо
Из недостатков только недостаточное разбиение ответственности, что в Translator, что в Program

2024-07-22 07:38 UTC, daug32 commented on backend/Dictionary/Translator/Translator/Translator.cs
> +    class Translator
Указывай, пожалуйста, модификаторы доступа всегда

2024-07-22 07:38 UTC, daug32 commented on backend/Dictionary/Translator/Translator/Translator.cs
> +                Console.WriteLine( "Слова нет в словаре" );
За подход с созданием сущности, управляющей переводами, большой плюс, а за то, что он пишет в консоль минус) 
Не до конца ответственность разделена
Рекомендую всё, что занимается user input/output вытаскивать в основную прогу. Или еще луцчше -- выделять в отдельный обработчик, это позволит более просто переехать на файлы с переводами для статических текстов типа "Слова нет в словаре", "Введите слово для удаления", переехать на условные вебсокеты и тд, а также упростит поиск этих текстов

2024-07-22 07:38 UTC, daug32 commented on backend/Dictionary/Translator/Translator/Translator.cs
> +                    writer.WriteLine( pair.Key + "," + pair.Value );
Используй лучше строковую интерполяцию, она выглядит читаемее

2024-07-22 07:38 UTC, daug32 commented on backend/Dictionary/Translator/Translator/Program.cs
> +                    Console.WriteLine( "Введите слово и его перевод через запятую:" );
Я уже видел проекты, где команды условного бота/консольного приложения обрабатываются через огромный switch. Менять там что-то очень больно) 
Критично: Разбей, пожалуйста, обработку каждой команды на отдельные методы. Это, во-первых, синтаксически обозначит, что происходит, а во-вторых изолирует все переменные

2024-07-24 01:46 UTC, L4pki commented on backend/Dictionary/Translator/Translator/Translator.cs
> +                Console.WriteLine( "Слова нет в словаре" );
Не уверен в том, что до конца понял комментарий, буду рад если посмотрите еще раз. Вкратце вынес тексты в отдельный класс и создал сущность для их вывода.

2025-01-29 13:46 UTC, merged